spring.application.name=backend

# ===== MySQL DataSource =====
spring.datasource.url=jdbc:mysql://localhost:3306/iot_monitor?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Chay data.sql SAU KHI Hibernate tao bang
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ===== MQTT Mosquitto Broker =====
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=SpringBootBackend
mqtt.username=datnguyen
mqtt.password=123456

# ===== JWT =====
jwt.secret=IoTSensorMonitorSystem2026SecretKeyForHS256MustBe256BitsLong!!
jwt.expiration=86400000

# ===== SpringDoc OpenAPI =====
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
